### ISSUE TITLE
NEXTEUROPA-12288: Enable Composer support for sub-sites

### ISSUE THREAD

**Issue by ademarco** [ec-europa/subsite-starterkit#15]
At the moment only the Multisite core platform developers can can benefit from Composer: dependencies are downloaded at a platform level, i.e. all sub-sites now shares the same third-party libraries.

Many sub-sites will soon need to use third-party Composer libraries too (some of them are already considering doing so) and, as a result, the current core-only approach is no longer sustainable.

**Comment by ademarco** [comment]
@pfrenssen @haringsrob @jfhovinne @degliwe could you please have a look at the referenced PR and tell me what do you think about? Thanks!

**Comment by mathiasselleslach** [comment]
Closing as the PR was merged and docu updated.
