### ISSUE TITLE
Panels shouldn't be in site.make

### ISSUE THREAD

**Issue by tatarbj** [ec-europa/subsite-starterkit#8]
Now the basic site.make file what supposed to be an example file in order to be used to put there contrib modules what subsites need has panels, what it shouldn't, at most commented.

**Comment by mathiasselleslach** [comment]
@tatarbj ,
This will be fixed with MULTISITE-12189.
Should be done today / tomorrow. :)

**Comment by mathiasselleslach** [comment]
Closing this issue, as this was resolved by renaming the site.make to site.make.example and make the use of the site.make file optional.
